x86: Include libcflat.h in atomic.h for u64 typedef
Include libcflat.h in x86's atomic.h to pick up the u64 typedef, which is
used to define atomic64_t.  The missing include results in build errors if
a test includes atomic.h without (or before) libcflat.h.

  lib/x86/atomic.h:162:1: error: unknown type name ‘u64’
  162 | u64 atomic64_cmpxchg(atomic64_t *v, u64 old, u64 new);

Signed-off-by: Sean Christopherson <seanjc@google.com>